apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
  namespace: {{ .Values.namespace.name }}
spec:
  containers:
  - name: postgres-client
    image: bitnami/postgresql:latest
    command:
    - sh
    - -c
    - |
      apt-get update
      apt-get install -y curl
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      sleep infinity