apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-legislators-processor
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: legislators-processor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP