namespace:
  name: rep-list

cronjob:
  schedule: "0 * * * *"
  image: travops87/officiallist:latest

postgres:
  namespace: postgres
  database: official
  username: admin
  password: admin
  service:
    port: 5432
